# Play nice with Docker on OSX
host: 0.0.0.0

name: Charles Fyfe
title: Charles Fyfe
description: "Personal website of Charles Fyfe"
url: 'https://charles.uno'
baseurl: ''
github: 'https://github.com/charles-uno'
author:
    name: Charles Fyfe
google_analytics: 'G-FQT93GWL1H'
permalink: /:title/
plugins:
  - jekyll-seo-tag
sass:
  sass_dir: /assets/_sass
  style: :compressed
  quiet_deps: true
  silence_deprecations:
    - import
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - CNAME
markdown: kramdown
kramdown:
  input: GFM
